spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:app_pw}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

app:
  pythonServiceBaseUrl: ${PY_SERVICE_BASEURL:http://localhost:8000}
